### ISSUE TITLE
[XI]LookInside sample fails with build error "error : Unexpected character ']' with d15-6

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/ios-samples#204] opened 2018-01-15 11:27 UTC
Moving https://github.com/xamarin/xamarin-macios/issues/3195 here since it has been confirmed not to be a XI bug.

### Steps to Reproduce

1. Open LookInside sample, ios-samples/ios8/LookInside
2. Build it

### Expected Behavior
App should build successfully

### Actual Behavior
App fails to build with an error "error : Unexpected character ']'. This issue occurs with d15-6 builds and not with d15-5  (11.6.X builds)

### Environment
```
=== Xamarin.iOS ===

Version: xamarin.ios-11.8.0.8 (Visual Studio Community)
Branch: xcode9.2

```
### Build Logs

Build Log with Stable: https://gist.github.com/GouriKumari/be22288e296816c93308cd9895563291
Build Log with error: https://gist.github.com/GouriKumari/8ecb3da1d10744d46c35f8f726cfaa8d

**Comment by bradumbaugh** [comment] 2018-07-05 17:17
Hi @mandel-macaque – I cannot reproduce ths issue using VSMac 7.5.3 or Visual Studio 2017 15.7.3. Going to close this out. Thanks!

**Comment by Blankys** [comment] 2018-08-16 20:01
Hi guys! I'm getting the same error, my jSON is valid but I don't know how to solve it :(, any ideas?

**Comment by bradumbaugh** [comment] 2018-08-16 21:34
Hi @Blankys – what specific error are you seeing? The same as above?

> obj/iPhoneSimulator/Debug/device-builds/iphone10.4-11.2/actool/cloned-assets/Resources/Images.xcassets/BigFlower.imageset/Contents.json(13,2,13,2): error : Unexpected character ']'. At line 13, column 2

**Comment by mandel-macaque** [comment] 2018-08-22 11:01
@Blankys can you please provide use with the full information of your environment. The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

With that info we will try to pin point when the error started happening and will try ti provide a fix. @bradumbaugh  we should try this with the latest stable and d15-8 to see if it happens since Mono was bumped.

**Comment by bradumbaugh** [comment] 2018-08-26 18:00
@mandel-macaque This app is building / running correctly with the latest Xamarin preview for Xcode 10.

**Comment by bradumbaugh** [comment] 2018-08-28 15:04
Closing this for now. @Blankys please feel free to re-open if you're still having trouble. Thank you!

**Closed by bradumbaugh** 2018-08-28 15:04 UTC
